import Head from "next/head";
import Header from "../sections/Header";
import Services from "../sections/Services";
import Work from "../sections/Work";
import Skills from "../sections/Skills";
import About from "../sections/About";
import Footer from "../sections/Footer";
import React from "react";
import { client } from "../lib/client";

const Home = ({ projects }) => {
  return (
    <div>
      <Head>
        <title>Salman Haider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coding.png" />
      </Head>
      <Header />
      <Services />
      <Work works={projects} />
      <Skills />
      <About />
      <Footer />
    </div>
  );
};

export const getServerSideProps = async () => {
  const query = '*[_type == "works"]';
  const projects = await client.fetch(query);

  return {
    props: { projects },
  };
};

export default Home;
